[1주차/머랭] 워크북 제출합니다.
UMC-Inha/7th_Spring pull request #15
Opened 2024-09-24 17:41 UTC by meoraeng

## ✅ 워크북 체크리스트

- [ ] 모든 핵심 키워드 정리를 마쳤나요?
- [ ] 핵심 키워드에 대해 완벽히 이해하셨나요?
- [ ] 이론 학습 이후 직접 실습을 해보는 시간을 가졌나요?
- [ ] 미션을 수행하셨나요?
- [ ] 미션을 기록하셨나요?

## ✅ 컨벤션 체크리스트

- [ ] 디렉토리 구조 컨벤션을 잘 지켰나요?
- [ ] pr 제목을 컨벤션에 맞게 작성하였나요?
- [ ] pr에 해당되는 이슈를 연결하였나요?(중요)
- [ ] 적절한 라벨을 설정하였나요?
- [ ] 파트장에게 code review를 요청하기 위해 reviewer를 등록하였나요?
- [ ] 닉네임/main 브랜치의 최신 상태를 반영하고 있는지 확인했나요?(매우 중요!)

## 📌 주안점

2024-09-25 09:46 UTC, qmean reviewed
고생하셨습니다 머랭! 지금 밖이라 집가서 빠르게 리뷰해드릴게요!
라벨만 붙여주시면 감사하겠습니다!

2024-09-25 11:20 UTC, qmean approved these changes
고생하셨습니다 머랭! 키워드 미션과 더불어 추가과제까지 예제코드로 너무 잘 작성해주신것 같습니다! 머지해 주시면 되겠습니다 👍

2024-09-25 11:21 UTC, qmean reviewed
엇 제가 타겟브랜치를 못봤었네요.. 타겟 브랜치만 수정해 주시면 감사하겠습니다!

2024-09-25 11:24 UTC, qmean requested changes
혹시몰라서.. 일단 머지 막아둘게요

2024-09-26 02:32 UTC, meoraeng commented
아차.. 브랜치 체크를 못했군요
브랜치 변경하고 라벨 달아뒀습니다 !

2024-09-26 04:44 UTC, qmean approved these changes
넵 고생하셨습니다! 머지해주시면 됩니다!

2024-09-26 06:13 UTC, merged