[1주차/져니] 워크북 제출합니다.
UMC-Inha/7th_Spring pull request #21
Opened 2024-09-26 15:20 UTC by jlhyunii

## ✅ 워크북 체크리스트

- [ ] 모든 핵심 키워드 정리를 마쳤나요?
- [ ] 핵심 키워드에 대해 완벽히 이해하셨나요?
- [ ] 이론 학습 이후 직접 실습을 해보는 시간을 가졌나요?
- [ ] 미션을 수행하셨나요?
- [ ] 미션을 기록하셨나요?

## ✅ 컨벤션 체크리스트

- [ ] 디렉토리 구조 컨벤션을 잘 지켰나요?
- [ ] pr 제목을 컨벤션에 맞게 작성하였나요?
- [ ] pr에 해당되는 이슈를 연결하였나요?(중요)
- [ ] 적절한 라벨을 설정하였나요?
- [ ] 파트장에게 code review를 요청하기 위해 reviewer를 등록하였나요?
- [ ] 닉네임/main 브랜치의 최신 상태를 반영하고 있는지 확인했나요?(매우 중요!)

## 📌 주안점

2024-09-26 23:52 UTC, qmean reviewed
져니 고생 많으셨습니다!
다만 미션 관련 커밋이 안보이는데 한번 확인 부탁해주시면 감사하겠습니다
혹시 로컬에 가지고 계신다면 push 해주세요!

2024-09-27 03:32 UTC, qmean reviewed
져니 죄송하지만 혹시 워크북 미션도 안보여서 그런데 올려주실 수 있나요?
사진파일 올리시고 커밋하시면 됩니다!

2024-09-27 04:44 UTC, jlhyunii commented
넵 뒤늦게 완료해서 이제 커밋했습니다! 죄송합니다ㅠ

2024-09-27 04:55 UTC, qmean approved these changes
넵 확인했습니다! 머지해주시면 됩니다!

2024-09-27 07:03 UTC, qmean requested changes
져니 제가 놓쳤는데 이슈 연결 부탁드립니다!

2024-09-27 08:02 UTC, qmean approved these changes
확인했습니다!

2024-09-27 08:03 UTC, merged